### PR TITLE
Move `contrib` to `root/opt/app-root` and update common

### PR DESCRIPTION
**Pull request by torsava**
common-container-scripts new automatically compile the README.md file into a
help.1 and place it into the root subdirectory to be copied to the image during
build.

Since in the Dockerfile the `contrib` directory was copied into two locations instead of the usual one, I added a symlink that gets copied into the image. The ultimate directory structure is a little bit different: `/opt/openshift` is a symlink to `/opt/app-root` and thus it contains the `etc`  subdirectory as previously, but also `src`.

All tests are passing on my machine.

### CODE REVIEW

**Comment by omron93** [comment]
@hhorak @notroj Do you know why `contrib/` was copied into two locations?

**Comment by torsava** [comment]
> Do you know why contrib/ was copied into two locations?

It's already in the initial commit. Do we know if and where the sources were tracked before?

**Comment by torsava** [comment]
I've added a commit removing the obsolete `/opt/openshift/' copy location.

**Comment by omron93** [comment]
Thanks.

LGTM + tests are passing

**Pull request merged**
