### PR TITLE
Update Dockerfiles

### PR DESCRIPTION
**Pull request by omron93**
Provide same labels for all base image variants (CentOS, RHEL, Fedora)
    - add name, version, summary and description labels
    - remove architecture label for RHEL based images (this label is set in RHE$

(don't use separate instruction for each label)

@jorton Any suggestions about values of summary and description?

@hhorak @praiskup @pkubatrh Please take a look and merge.

### CODE REVIEW

**Comment by pkubatrh** [comment]
Missing backslashes in DESCRIPTION

**Comment by omron93** [comment]
Fixed, thanks.

**Comment by pkubatrh** [comment]
>io.k8s.description="DESCRIPTION"

missing $ before DESCRIPTION ^, otherwise LGTM.

**Comment by omron93** [comment]
Thanks for catching this. It is fixed now.

**Comment by pkubatrh** [comment]
Thanks, merging.

**Pull request merged**
